service: aws-python-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: ap-northeast-2
  runtime: python3.6 # or python3.7, supported as of November 2018

package:
  exclude:
    - venv/**

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: chatbot
          method: post
